language: python
python:
  - "3.7"
virtualenv:
  system_site_packages: true
# command to install dependencies
install:
  - pipenv install -r requirements.txt
  - pipenv install .
# command to run tests
script: pytest